### PR TITLE
Headbar, Navbar and React Router

### PR DESCRIPTION
**Pull request by jingjingwangacc**
# Summary

This pull request setup headbar, navbar, sidebars. React frameworks setup, need to work on the detailed react frontend pages.

## Type of Change

- [ ] Bug fix

- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing Steps

1. Pull PR Branch
2. Run `npm install`
3. Create a `.env` file
4. Run `npm run build`
5. Run `npm run start`
6. Navigate to [localhost:3000](http://localhost:3000)
7. Run `npm run dev`
8. Navigate to [localhost:8000](http://localhost:8000)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by wenzhen-gong — COMMENTED** [review]
@Joel-Christopher Do you think it is safe to merge these changes into electron?

**Review by Joel-Christopher — APPROVED** [review]
Looks good

**Comment by Joel-Christopher** [comment]
> @Joel-Christopher Do you think it is safe to merge these changes into electron?

This should be good. We will need to modify some code within main.js and the files path it points too for index.html

**Review by michael-w-mann — APPROVED** [review]
Excited to dive into this - MM

**Pull request merged**
